name: toycloud

services:
  webservice:
    build:
      context: ./
      dockerfile: ./webservice/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
  loadbalancer:
    container_name: loadbalancer-1
    build:
      context: ./
      dockerfile: ./loadbalancer/Dockerfile
    ports:
      - "8080:8080"
  servicediscovery:
    container_name: servicediscovery
    build:
      context: ./
      dockerfile: ./servicediscovery/Dockerfile
  orchestrator:
    container_name: orchestrator
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock